#!/usr/bin/env bash

get_bat_info() {

    read -r bat_percent \
            bat_time \
            < <(awk '{ print $1, $3 }' <<< "${bat_cache[1]}")

    bat_percent="${bat_percent/;/}"

    bat_state="$(awk '/Now/ { print $4 }' <<< "${bat_cache[0]}")"
    bat_state="${bat_state#\'}"
    [[ "$bat_state" != "AC" ]] && bat_state="Discharging"

    if [[ "$bat_time" == "(no" || "$bat_time" == "charge;" ]]; then
        bat_time="Indeterminate"
    else
        bat_time="${bat_time} remaining"
    fi

    [[ "$bat_time" == "0:00 remaining" && "$bat_state" == "AC" ]] && bat_time="Fully charged"

    bat_temp="$(istats battery temp --value-only)"

    read -r bat_cycles \
            bat_condition \
            <\
            <(awk  '/Cycle Count/ { a=$3 }
                    /Condition/ { print a, $2 }' <<< "${bat_cache[2]}")

}

format_notification() {

    title="Battery (${bat_percent})"
    subtitle="${bat_time} | ${bat_temp// }°C | ${bat_condition} | ${bat_cycles} cycles"
    content="${bat_state}"

}

main() {

    bat_cache+=("$(pmset -g batt)")
    bat_cache+=("$(grep -E "([0-9]+\\%).*" -o <<< "${bat_cache[0]}")")
    bat_cache+=("$(system_profiler SPPowerDataType)")
    get_bat_info
    format_notification
    terminal-notifier -title "${title:-}" \
                      -subtitle "${subtitle:-}" \
                      -message "${content:-}"

}

main
