#!/usr/bin/env bash

get_mem() {

    vm_stat_cache="$(vm_stat)"
    mem_total="$(($(sysctl -n hw.memsize) / 1024 / 1024))"
    mem_wired="$(awk '/wired/ { print $4 }' <<< "${vm_stat_cache}")"
    mem_active="$(awk '/active / { printf $3 }' <<< "${vm_stat_cache}")"
    mem_compressed="$(awk '/occupied/ { printf $5 }' <<< "${vm_stat_cache}")"
    mem_used="$(((${mem_wired//.} + ${mem_active//.} + ${mem_compressed//.}) * 4 / 1024))"
    printf "%s\\n" "${mem_used}MiB | ${mem_total}MiB"

}

get_swap() {

    trim_digits() {
        case "${1##*.}" in
            "00")   printf "%s" "${1/.*}" ;;
            *)      printf "%s" "${1}" ;;
        esac
    }

    swap_cache="$(sysctl vm.swapusage)"
    swap_total="$(awk '{ print $4 }' <<< "${swap_cache}")"
    swap_used="$(awk '{ print $7 }' <<< "${swap_cache}")"

    swap_total="$(trim_digits "${swap_total/M*}")"
    swap_used="$(trim_digits "${swap_used/M*}")"

    swap_usage="${swap_used}MiB | ${swap_total}MiB"
    printf "%s\\n" "${swap_usage}"

}

format_notification() {

    title="Memory"
    subtitle="$(get_mem)"
    content="Swap: $(get_swap)"

}

main() {

    source "${0%/*}/notify"
    format_notification
    notify "${title}" "${subtitle}" "${content}"

}

main