#!/usr/bin/env bash

get_mem() {

    mem_total="$(($(sysctl -n hw.memsize) / 1024 / 1024))"

    read -r mem_wired \
            mem_compressed \
            < <(awk '/wired/ { a=$4 } /occupied/ { print a, $5 }' <<< "$(vm_stat)")

    mem_used="$(((${mem_wired//.} + ${mem_compressed//.}) * 4 / 1024))"
    printf "%s\\n" "${mem_used}MiB | ${mem_total}MiB"

}

get_swap() {

    trim_digits() {
        case "${1##*.}" in
            "00")   printf "%s" "${1/.*}" ;;
            *)      printf "%s" "${1}" ;;
        esac
    }

    read -r swap_total \
            swap_used \
            < <(awk '{ print $4, $7 }' <<< "$(sysctl vm.swapusage)")

    swap_total="$(trim_digits "${swap_total/M*}")"
    swap_used="$(trim_digits "${swap_used/M*}")"

    swap_usage="${swap_used}MiB | ${swap_total}MiB"
    printf "%s\\n" "${swap_usage}"

}

format_notification() {

    title="Memory"
    subtitle="$(get_mem)"
    content="Swap: $(get_swap)"

}

main() {

    format_notification
    terminal-notifier -title "${title:-}" \
                      -subtitle "${subtitle:-}" \
                      -message "${content:-}"

}

main