#!/usr/bin/env bash

get_cpu() {

    cpu="$(sysctl -n machdep.cpu.brand_string)"
    export cores
    cpu="${cpu/@/(${cores}) @}"
    printf "%s\\n" "${cpu}"

}

get_load() {

    load="$(sysctl -n vm.loadavg)"
    load="${load/' }'}"
    load="${load/'{ '}"
    printf "%s\\n" "${load}"

}

get_cpu_usage() {

    cpu_usage="$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')"
    cpu_usage="$((${cpu_usage/\.*} / ${cores:-1}))%"
    printf "%s\\n" "${cpu_usage}"

}

get_temp() {

    temp="$(osx-cpu-temp)"
    printf "%s\\n" "${temp}"

}

get_fan_speed() {

    fan="$(istats fan --value-only | awk 'NR==2{print;exit}')"
    fan="${fan// }RPM"
    printf "%s\\n" "${fan}"

}

get_uptime() {

    strip() {
        case "$2" in
            "0")    unset "$1" ;;
            *)      printf "%s" "$2${1:0:1} " ;;
        esac
    }

    boot="$(sysctl -n kern.boottime)"
    boot="${boot/'{ sec = '}"
    boot="${boot/,*}"
    seconds="$(($(date +%s) - boot))"

    days="$(strip days $((seconds / 60 / 60 / 24)))"
    hours="$(strip hours $((seconds / 60 / 60 % 24)))"
    mins="$(strip mins $((seconds / 60 % 60)))"
    secs="$(strip secs $((seconds % 60 % 60 % 24)))"
    uptime="${days}${hours}${mins}${secs}"
    printf "%s\\n" "${uptime}"

}

format_notification() {

    cores="$(sysctl -n hw.logicalcpu_max)"
    title="$(get_cpu)"
    subtitle="Load avg: $(get_load) | $(get_cpu_usage) | $(get_temp) | $(get_fan_speed)"
    ((${#subtitle} >= 50)) && subtitle="${subtitle/ avg/}"
    ((${#subtitle} >= 50)) && subtitle="${subtitle/Load: /}"
    content="Uptime: $(get_uptime)"

}

get_model() {

    model="$(sysctl -n hw.model)"
    icon_path="/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources"

    case "$model" in
        "MacBook1,1"| \
        "MacBook2,1"| \
        "MacBook3,1"| \
        "MacBook4,1"| \
        "MacBook5,2")       icon_path="${icon_path}/com.apple.macbook-white.icns" ;;
        "MacBook6,1"|\
        "MacBook7,1")       icon_path="${icon_path}/com.apple.macbook-unibody-plastic.icns" ;;
        "MacBook5,1")       icon_path="${icon_path}/com.apple.macbook-unibody.icns" ;;
        "MacBook8,1"| \
        "MacBook9,1"| \
        "MacBook10,1")      icon_path="${icon_path}/com.apple.macbook-retina-silver.icns" ;;
        "MacBookAir1,1"| \
        "MacBookAir2,1")    icon_path="${icon_path}/com.apple.macbookair.icns" ;;
        "MacBookAir"*)
            case "${model:12:1}" in
                "1") icon_path="${icon_path}/com.apple.macbookair-11-unibody.icns" ;;
                "2") icon_path="${icon_path}/com.apple.macbookair-13-unibody.icns" ;;
            esac
        ;;
        "MacBookPro1,1"| \
        "MacBookPro2,2"| \
        "MacBookPro3,1"| \
        "MacBookPro4,1") icon_path="${icon_path}/com.apple.macbookpro-15.icns" ;;
        "MacBookPro1,2"| \
        "MacBookPro2,1") icon_path="${icon_path}/com.apple.macbookpro-17.icns" ;;
        "MacBookPro"*)
            case "${model:10:4}" in
                "5,2"| \
                "6,1"| \
                "8,3") icon_path="${icon_path}/com.apple.macbookpro-17-unibody.icns" ;;
                "5,1"| \
                "5,3"| \
                "5,4"| \
                "6,2"| \
                "8,2"| \
                "9,1") icon_path="${icon_path}/com.apple.macbookpro-15-unibody.icns" ;;
                "5,5"| \
                "7,1"| \
                "8,1"| \
                "9,2") icon_path="${icon_path}/com.apple.macbookpro-13-unibody.icns" ;;
                "10,1"| \
                "11,2"| \
                "11,3"| \
                "11,2"| \
                "11,3"| \
                "11,4"| \
                "11,5") icon_path="${icon_path}/com.apple.macbookpro-15-retina-display.icns" ;;
                "10,2"| \
                "11,1"| \
                "12,1") icon_path="${icon_path}/com.apple.macbookpro-13-retina-display.icns" ;;
                *)
                    case "${model:13:4}" in
                        "1") icon_path="${icon_path}/com.apple.macbookpro-13-retina-usbc-silver.icns" ;;
                        "2") icon_path="${icon_path}/com.apple.macbookpro-13-retina-touchid-silver.icns" ;;
                        "3") icon_path="${icon_path}/com.apple.macbookpro-15-retina-touchid-silver.icns" ;;
                    esac
                ;;
            esac
        ;;
    esac
    printf "%s\\n" "${icon_path}"
}

main() {

    format_notification
    terminal-notifier -title "${title:-}" \
                      -subtitle "${subtitle:-}" \
                      -message "${content:-}" \
                      #-appIcon "$(get_model)"

}

main
