#!/usr/bin/env bash

# Send a notification
title="chunkwm"
subtitle=""
content="Restarting chunkwm"
terminal-notifier -title "${title:-}" \
                  -subtitle "${subtitle:-}" \
                  -message "${content:-}" \
                  -sound default

# Restart chunkwm
brew services restart chunkwm